import "./globals.css";

export const metadata = {
  title: "Investigation Details",
  description: "Generated by ~Shaheen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
